### ISSUE TITLE
Pro / Explore (+2)

### ISSUE THREAD

**Issue by PavelShir** [PavelShir/EventHubApp#16]
Под категориями добавлена коллекция с тремя кнопками:

TODAY: события, проходящие сегодня.
FILMS: список фильмов.
LISTS: подборки, открывающиеся в веб-браузере при нажатии на READ.

**Comment by AnnaMelekh** [comment]
TODAY: фильтр по currentDate 
FILMS:  https://kudago.com/public-api/v1.4/movies/?actual_since={{$timestamp}}
LISTS:  https://kudago.com/public-api/v1.2/lists/
